name: Pytest-All

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.9
    - name: Install dependencies & test
      run: |
        python -m venv .
        source bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest qbnb_test
